# Author : portalsurfer <https://github.com/PORTALSURFER>

inherits = "hex_steel"

[palette]
t1 = "#121211"
t2 = "#1e1f1b"
t3 = "#4c513a"
t4 = "#5a6052"
t5 = "#6f6d6f"
t6 = "#7e808a"
t7 = "#b1b354"
t8 = "#a0abb8"
t9 = "#b6b8bc"
t10 = "#bec7c6"
t11 = "#72fae9"

highlight = "#ff2e5f"
highlight_two = "#0affa9"
highlight_three = "#d7ff52"

black = "#000000"

selection = "#290019"

comment = "#396884"
comment_doc = "#234048"

error = "#ff0900"
warning = "#ffbf00"
display = "#57ff89"
info = "#dad7d5"

hints = "#313d3c"
ruler  = "#21221e"

diff_minus = "#ff4000"
diff_delta = "#0078bd"
diff_plus = "#c9d400"
diff_delta_moved = "#0048bd"